include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    avoid_print: ignore
    library_private_types_in_public_api: ignore
    non_constant_identifier_names: ignore

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
