name: flex_track
description: A flexible analytics tracking system for Flutter with intelligent routing, GDPR compliance, and multi-platform support
version: 0.1.1  # Use semantic versioning
homepage: https://github.com/alirezat66/flex_track
repository: https://github.com/alirezat66/flex_track
issue_tracker: https://github.com/alirezat66/flex_track/issues
documentation: https://github.com/alirezat66/flex_track#readme

topics:
  - analytics
  - tracking
  - gdpr
  - routing
  - flutter

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.0.0 # Use mockito instead of mocktail
  build_runner: ^2.0.0 # Add build_runner for mock generation

flutter: {}


